from enum import Enum, auto


class WType(Enum):
    """
    WType is a class that defines the type of a Wwise object.
    """
    AcousticTexture = auto()
    Action = auto()
    ActionException = auto()
    ActorMixer = auto()
    Attenuation = auto()
    AudioDevice = auto()
    AudioSource = auto()
    AuxBus = auto()
    BlendContainer = auto()
    BlendTrack = auto()
    Bus = auto()
    ControlSurfaceBinding = auto()
    ControlSurfaceBindingGroup = auto()
    ControlSurfaceSession = auto()
    Conversion = auto()
    Curve = auto()
    CustomState = auto()
    DialogueEvent = auto()
    Effect = auto()
    Event = auto()
    ExternalSource = auto()
    ExternalSourceFile = auto()
    Folder = auto()
    GameParameter = auto()
    Language = auto()
    Metadata = auto()
    MidiParameter = auto()
    MixingSession = auto()
    Modifier = auto()
    ModulatorEnvelope = auto()
    ModulatorLfo = auto()
    ModulatorTime = auto()
    MultiSwitchEntry = auto()
    MusicClip = auto()
    MusicClipMidi = auto()
    MusicCue = auto()
    MusicEventCue = auto()
    MusicFade = auto()
    MusicPlaylistContainer = auto()
    MusicPlaylistItem = auto()
    MusicSegment = auto()
    MusicStinger = auto()
    MusicSwitchContainer = auto()
    MusicTrack = auto()
    MusicTrackSequence = auto()
    MusicTransition = auto()
    ObjectSettingAssoc = auto()
    Panner = auto()
    ParamControl = auto()
    Path = auto()
    Platform = auto()
    PluginDataSource = auto()
    Position = auto()
    Project = auto()
    Query = auto()
    RandomSequenceContainer = auto()
    SearchCriteria = auto()
    Sound = auto()
    SoundBank = auto()
    SoundcasterSession = auto()
    State = auto()
    StateGroup = auto()
    Switch = auto()
    SwitchContainer = auto()
    SwitchGroup = auto()
    Trigger = auto()
    UserProjectSettings = auto()
    WorkUnit = auto()


if __name__ == '__main__':
    print(WType.AcousticTexture)
    print(WType.AcousticTexture.name)
    print(WType.AcousticTexture.value)